CREATE INDEX "I_CAPACITY_FUNC_BASED" ON "LOCATION_SITE_CAPACITY" ("LOCATION", "SITE", "EMPLOYEE", "PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("WORK_DATE","HOUR","MINUTE"));

CREATE INDEX "I_CLOSING_FUNCTION_BASED" ON "AC_ACTUAL_FLIGHTS" ("AC", "PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("FLIGHT_DATE",DECODE("OFF_HOUR"+"OFF_MINUTE",0,"TO_HOUR","OFF_HOUR"),DECODE("OFF_HOUR"+"OFF_MINUTE",0,"TO_MINUTE","OFF_MINUTE")));

CREATE INDEX "I_TRNSCTION_HISTORY_CLOSING" ON "AC_PN_TRANSACTION_HISTORY" ("AC", "PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("TRANSACTION_DATE","TRANSACTION_HOUR","TRANSACTION_MINUTE"));

CREATE INDEX "I_AC_ACTUALS_CLOSING" ON "AC_ACTUAL_FLIGHTS" ("AC", "PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("FLIGHT_DATE","OFF_HOUR","OFF_MINUTE"));

CREATE INDEX "I_FLIGHT_SCHEDULE_CHRONO" ON "FLIGHT_SCHEDULE" ("AC", "PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("SCHEDULE_DATE","SCHEDULE_DEPART_HOUR_ZULU","SCHEDULE_DEPART_MINUTE_ZULU"));

CREATE INDEX "I_ENGINRING_COMPLIANCE_CLOSING" ON "ENGINEERING_COMPLIANCE" ("AC", "PN", "PN_SN", "PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("RESET_DATE","RESET_HOUR","RESET_MINUTE"));

CREATE INDEX "I_ENGINRING_EFFEC_CLOSING" ON "ENGINEERING_EFFECTIVITY" ("PN", "PN_SN", "PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("EFFECTIVE_DATE","EFFECTIVE_HOUR","EFFECTIVE_MINUTE"));

CREATE INDEX "FLIGHT_SCHEDULE_COMBINEDATE" ON "FLIGHT_SCHEDULE" ("PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("SCHEDULE_DATE",NVL("SCHEDULE_DEPART_HOUR_ZULU",0),NVL("SCHEDULE_DEPART_MINUTE_ZULU",0))); 

CREATE INDEX "I_AC_ACTUAL_FLIGHTS_LANDING" ON "AC_ACTUAL_FLIGHTS" ("AC", CEIL("PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("FLIGHT_DATE","OFF_HOUR","OFF_MINUTE")-"PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("FLIGHT_DATE","LDG_HOUR","LDG_MINUTE"))+"PKG_APPLICATION_FUNCTION"."GETCOMBINEDDATE"("FLIGHT_DATE","LDG_HOUR","LDG_MINUTE"));
